name: fall_game
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  # flame: ^1.10.1
  flame: ^1.12.0
  flame_forge2d: ^0.16.0+2
  #  flame_splash_screen: ^0.1.0
  flame_audio: ^2.1.5
  async: ^2.11.0
  flutter_launcher_icons: ^0.13.1
  games_services: ^3.0.2
  games_services_platform_interface: ^3.0.2
  shared_preferences: ^2.2.1
  shared_preferences_windows: ^2.2.0
  flutter_native_splash: ^2.3.2
  app_tracking_transparency: ^2.0.4
  url_launcher: ^6.1.14
  intl: ^0.18.0
  google_mobile_ads: ^3.0.0
  provider: ^6.0.5
  file: ^6.1.4
  supabase_flutter: ^2.0.0
  # supabase_flutter: ^1.10.25
  uuid: ^4.2.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  image: "assets/splash.png"
  color: "FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/1-icon.png
    - assets/images/2-icon.png
    - assets/images/3-icon.png
    - assets/images/4-icon.png
    - assets/images/5-icon.png
    - assets/images/6-icon.png
    - assets/images/7-icon.png
    - assets/images/8-icon.png
    - assets/images/9-icon.png
    - assets/images/10-icon.png
    - assets/images/11-icon.png
    - assets/images/back_background.png
    - assets/images/title.png
    - assets/images/start.png
    - assets/images/multi.png
    - assets/images/ranking.png
    - assets/images/post.png
    - assets/images/copyright.png
    - assets/images/menu.png
    - assets/images/game_over.png
    - assets/images/tap_title.png
    - assets/images/empty.png
    - assets/images/connect_0.png
    - assets/images/connect_1.png
    - assets/images/connect_2.png
    - assets/images/cancel.png
    - assets/audio/title.wav
    - assets/audio/bgm.wav
    - assets/audio/sfx/collision.wav
    - assets/audio/sfx/spawn.wav

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Square-L
      fonts:
        - asset: assets/fonts/Square-L.ttf
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
